---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Não
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Sim, é possível usando `cinemas.value_counts("setor")`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Sim, é possível usando `cinemas["screens"].sum()`
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Sim, é possível usando `cinemas.value_counts("setor").sum()`
  checked: false
name: Agrupe-se um pouco!
