---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: O nível de emprego não varia ao longo dos diferentes anos
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: As mulheres apresentam sempre uma taxa de emprego mais baixa do que os homens
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: As mulheres apresentam sempre uma taxa de emprego mais elevada do que os
    homens
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: As mulheres apresentam sempre a mesma taxa de emprego que os homens
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: As mulheres às vezes apresentam taxas de emprego mais altas do que os homens
    e outras vezes, mais baixas
  checked: false
name: Uma tabela não diz nada
