---
locale: pt
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: Agrupar de acordo com as infrações e calcular a média das placas
  checked: false
- value: Agrupar de acordo com as placas e calcular a média das infrações
  checked: true
- value: Agrupar de acordo com as placas e calcular a mediana das infrações
  checked: false
- value: Agrupar de acordo com as placas e calcular a menor das infrações
  checked: false
- value: Agrupar de acordo com as patentes e calcular o número de infrações
  checked: false
name: Agrupar, agrupar, cada coisa no seu lugar
