---
locale: es
tags: []
layout: input_bottom
editor: single_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: D치 erro
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Mostra um gr치fico de linha
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Mostra um gr치fico de barras
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: Mostra um gr치fico de pizza
  checked: false
name: Uma imagem em poucas palavras
