import numpy as np
import pandas as pd

cines = pd.DataFrame([
    {'loc_code': 82070050, 'prov_id': 82, 'dep_id': 82070, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Santa Fe', 'department': 'Las Colonias', 'city': 'Esperanza', 'name': 'E-Max Cines', 'address': 'Brigadier Lopez 1471', 'floor': 's/d', 'zip_code': 3080, 'area_code': '3496', 'sector': 'Privado comercial', 'screens': 3, 'seats': 584, 'update_year': 2018},
    {'loc_code': 6210020, 'prov_id': 6, 'dep_id': 6210, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'Chacabuco', 'city': 'Chacabuco', 'name': 'Cine Teatro Español', 'address': 'Pueyrredon 29', 'floor': 's/d', 'zip_code': 6740, 'area_code': '2352', 'sector': 'Privado comercial', 'screens': 1, 'seats': 700, 'update_year': 2018},
    {'loc_code': 2000010, 'prov_id': 2, 'dep_id': 2000, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Ciudad Autónoma de Buenos Aires', 'department': 'Ciudad Autonoma de Buenos Aires', 'city': 'Ciudad Autónoma de Buenos Aires', 'name': 'Sala Leopoldo Lugones', 'address': 'Av. Corrientes 1530', 'floor': 's/d', 'zip_code': 1042, 'area_code': 's/d', 'sector': 'Público municipal', 'screens': 1, 'seats': 212, 'update_year': 2018},
    {'loc_code': 2000010, 'prov_id': 2, 'dep_id': 2000, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Ciudad Autónoma de Buenos Aires', 'department': 'Ciudad Autonoma de Buenos Aires', 'city': 'Ciudad Autónoma de Buenos Aires', 'name': 'Sala Raúl González Tuñón', 'address': 'Av. Corrientes 1543', 'floor': 's/d', 'zip_code': 1042, 'area_code': 's/d', 'sector': 'Privado independiente', 'screens': 1, 'seats': 94, 'update_year': 2018},
    {'loc_code': 6638040, 'prov_id': 6, 'dep_id': 6638, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'Pilar', 'city': 'Pilar', 'name': 'Multiplex', 'address': 'Las Magnolias 754', 'floor': 'Piso 1', 'zip_code': 1629, 'area_code': '230', 'sector': 'Privado comercial', 'screens': 9, 'seats': 1407, 'update_year': 2018},
    {'loc_code': 6441030, 'prov_id': 6, 'dep_id': 6441, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'La Plata', 'city': 'La Plata', 'name': 'Cinema', 'address': 'Calle 49 621', 'floor': 's/d', 'zip_code': 1900, 'area_code': '221', 'sector': 'Privado comercial', 'screens': 6, 'seats': 1613, 'update_year': 2018},
    {'loc_code': 70028010, 'prov_id': 70, 'dep_id': 70028, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'San Juan', 'department': 'Capital', 'city': 'San Juan', 'name': 'Play Cinema', 'address': 'Av. Libertador 1826 (Oeste)', 'floor': 's/d', 'zip_code': 5400, 'area_code': '264', 'sector': 'Privado comercial', 'screens': 6, 'seats': 1071, 'update_year': 2018},
    {'loc_code': 6028010, 'prov_id': 6, 'dep_id': 6028, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'Almirante Brown', 'city': 'Adrogué', 'name': 'Cinemas Paseo Adrogué', 'address': 'Segui 699', 'floor': 's/d', 'zip_code': 1846, 'area_code': 's/d', 'sector': 'Privado comercial', 'screens': 4, 'seats': 710, 'update_year': 2018},
    {'loc_code': 6112010, 'prov_id': 6, 'dep_id': 6112, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Buenos Aires', 'department': 'Bragado', 'city': 'Bragado', 'name': 'Espacio Incaa Florencio Constantino', 'address': 'Belgrano 1260', 'floor': 's/d', 'zip_code': 6640, 'area_code': '2342', 'sector': 'Público municipal', 'screens': 1, 'seats': 750, 'update_year': 2018},
    {'loc_code': 66028050, 'prov_id': 66, 'dep_id': 66028, 'obs': np.nan, 'category': 'Salas de cine', 'province': 'Salta', 'department': 'Capital', 'city': 'Salta', 'name': 'Hogar Escuela', 'address': 'Pje. Chiclana Esq. H. Irigoyen S/N', 'floor': 's/d', 'zip_code': 4400, 'area_code': '387', 'sector': 'Público provincial', 'screens': 1, 'seats': 354, 'update_year': 2018}])
