---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
progressive_expectations: false
choices:
- value: "`plot.barh` permite fazer gráficos de pizza"
  checked: false
- value: "`plot.pie` permite fazer gráficos de pizza"
  checked: true
- value: "`value_counts` também retorna uma `Series` e por isso é possível usar seu
    resultado para fazer gráficos"
  checked: true
- value: Ao representar com gráficos, a ordem dos valores dentro de uma `Series` é
    irrelevante e não tem impacto no gráfico resultante
  checked: false
name: Traga a pipoca
