---
locale: pt
tags: []
layout: input_bottom
editor: multiple_choice
type: problem
extra_visible: false
language: text
teacher_info: ''
manual_evaluation: false
choices:
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`plot.barh` permite fazer gráficos de pizza"
  checked: false
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`plot.pie` permite fazer gráficos de pizza"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: "`value_counts` também retorna um `Series` e por isso é possível usar seu
    resultado para fazer gráficos"
  checked: true
- !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  value: ao representar com gráficos, a ordem dos valores dentro de um `Series` é
    irrelevante e não tem impacto no gráfico resultante
  checked: false
name: Traga a pipoca
